const std = @import("std");
const coeffs = @import("sim/support/swiglu_coeffs.zig");

pub fn main(init: std.process.Init) !void {
    var buffer: [4096]u8 = undefined;
    var stdout = std.Io.File.stdout().writerStreaming(init.io, &buffer);
    const out = &stdout.interface;
    try out.print("        // Generated by fpga/gen_section_swiglu_lut.zig; FNV64=0x{x:0>16}.\n", .{coeffs.coefficientHash()});
    for (0..coeffs.segment_count) |index| {
        const c = coeffs.coefficient(index);
        try out.print(
            "        coeff_rom[{d}] = 64'h{x:0>8}_{x:0>8};\n",
            .{ index, c.intercept_bits, c.slope_bits },
        );
    }
    try out.flush();
}
