// swiglu - scalar SwiGLU transform.
//
// The projection sink presents paired gate/up FP32 values in resident order. This
// leaf evaluates a 1/32-grid piecewise-linear SiLU over [-16,16), multiplies by UP,
// and preserves scalar order/TLAST. It deliberately does not contain a quantizer:
// shared_q8 owns the design's sole q8_pack4 instance.
//
// Interior approximation:
//   silu(g) ~= trunc_add(trunc_mul(g, slope[segment]), intercept[segment])
//   y        = trunc_mul(silu(g), up)
// Tails are exact guards in the chosen approximation: g <= -16 -> 0; g >= 16 -> g.
// The 1024 x 64 slope/intercept ROM is generated by
// fpga/build/generators/swiglu_lut.zig.
// Its committed FNV64 is checked by fpga/build/generators/swiglu_coeffs.zig.
//
// Status is per scalar and remains stable with out_valid under backpressure:
//   [0] gate or up was non-finite; both were replaced by zero
//   [1] the final truncating multiply reached its finite saturation code
// abort synchronously discards every partial, in-flight, and queued scalar.

`default_nettype none
/* verilator lint_off SYMRSVDWORD */

module swiglu #(
    parameter integer RESERVE_DEPTH = 64
) (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        abort,

    input  wire        in_valid,
    output wire        in_ready,
    output wire        in_ready_core,
    input  wire [31:0] in_gate,
    input  wire [31:0] in_up,
    input  wire        in_last,

    output reg         out_valid,
    input  wire        out_ready,
    output wire [31:0] out_data,
    output wire        out_last,
    output wire [1:0]  out_status
`ifdef FORMAL
    , output wire [6:0] formal_reserved_count
    , output wire [9:0] formal_fifo_count
    , output wire       formal_fifo_write_enable
    , output wire       formal_fifo_read_enable
`endif
);
    `include "fmt.vh"

    localparam [31:0] ZERO_F32 = 32'h0000_0000;
    localparam [31:0] ONE_F32  = 32'h3f80_0000;
    localparam [30:0] ABS_16   = 31'h4180_0000;
    localparam [30:0] MAX_FIN  = 31'h7f7f_ffff;
    // A 512-address circular store selects the native RAMB18 512x36 mode. The
    // independent reservation limit keeps the externally visible capacity at 64.
    localparam integer FIFO_DEPTH = 512;
    localparam integer FIFO_PTR_W = 9;

    // floor((g + 16) * 32) without an FP adder. Only finite |g| < 16 reaches
    // this function. Negative values use -ceil(|g|*32), so exact grid points
    // select the segment beginning at that point and all other values select
    // the segment immediately below them.
    function automatic [9:0] segment_index(input [31:0] value);
        reg [23:0] sig;
        reg [8:0] mag_floor;
        reg has_fraction;
        reg [9:0] mag_ceil;
        begin
            sig = {1'b1, value[22:0]};
            mag_floor = 9'd0;
            has_fraction = |value[30:0];
            case (value[30:23])
                8'd122: begin mag_floor = {8'd0, sig[23]};       has_fraction = |sig[22:0]; end
                8'd123: begin mag_floor = {7'd0, sig[23:22]};    has_fraction = |sig[21:0]; end
                8'd124: begin mag_floor = {6'd0, sig[23:21]};    has_fraction = |sig[20:0]; end
                8'd125: begin mag_floor = {5'd0, sig[23:20]};    has_fraction = |sig[19:0]; end
                8'd126: begin mag_floor = {4'd0, sig[23:19]};    has_fraction = |sig[18:0]; end
                8'd127: begin mag_floor = {3'd0, sig[23:18]};    has_fraction = |sig[17:0]; end
                8'd128: begin mag_floor = {2'd0, sig[23:17]};    has_fraction = |sig[16:0]; end
                8'd129: begin mag_floor = {1'd0, sig[23:16]};    has_fraction = |sig[15:0]; end
                8'd130: begin mag_floor = sig[23:15];            has_fraction = |sig[14:0]; end
                default: begin mag_floor = 9'd0; has_fraction = |value[30:0]; end
            endcase
            mag_ceil = {1'b0, mag_floor} + (has_fraction ? 10'd1 : 10'd0);
            segment_index = value[31]
                ? (10'd512 - mag_ceil)
                : (10'd512 + {1'b0, mag_floor});
        end
    endfunction

    (* rom_style = "block" *) reg [63:0] coeff_rom [0:1023];
    initial begin
        // Generated by fpga/build/generators/swiglu_lut.zig; FNV64=0x3c259838fbe85a1b.
        coeff_rom[0] = 64'hb7f500ee_b5e5e640;
        coeff_rom[1] = 64'hb7fbcb07_b5ecb3c0;
        coeff_rom[2] = 64'hb8016283_b5f3b4c0;
        coeff_rom[3] = 64'hb804f7fb_b5faea80;
        coeff_rom[4] = 64'hb808a66f_b6012b20;
        coeff_rom[5] = 64'hb80c6ec3_b604fd00;
        coeff_rom[6] = 64'hb81051b6_b608ebc0;
        coeff_rom[7] = 64'hb8144fcb_b60cf800;
        coeff_rom[8] = 64'hb81869e0_b61122c0;
        coeff_rom[9] = 64'hb81ca0b2_b6156ce0;
        coeff_rom[10] = 64'hb820f4ff_b619d740;
        coeff_rom[11] = 64'hb825679f_b61e62e0;
        coeff_rom[12] = 64'hb829f96c_b62310c0;
        coeff_rom[13] = 64'hb82eaafd_b627e1a0;
        coeff_rom[14] = 64'hb8337d89_b62cd6e0;
        coeff_rom[15] = 64'hb83871c3_b631f160;
        coeff_rom[16] = 64'hb83d887c_b6373220;
        coeff_rom[17] = 64'hb842c2e5_b63c9a80;
        coeff_rom[18] = 64'hb84821cc_b6422b80;
        coeff_rom[19] = 64'hb84da5ff_b647e620;
        coeff_rom[20] = 64'hb85350e4_b64dcc00;
        coeff_rom[21] = 64'hb8592346_b653de20;
        coeff_rom[22] = 64'hb85f1e0c_b65a1da0;
        coeff_rom[23] = 64'hb86542b3_b6608c40;
        coeff_rom[24] = 64'hb86b9220_b6672b20;
        coeff_rom[25] = 64'hb8720d54_b66dfb80;
        coeff_rom[26] = 64'hb878b5e4_b674ff40;
        coeff_rom[27] = 64'hb87f8cac_b67c3780;
        coeff_rom[28] = 64'hb8834973_b681d2e0;
        coeff_rom[29] = 64'hb886e51d_b685a600;
        coeff_rom[30] = 64'hb88a99b3_b68995a0;
        coeff_rom[31] = 64'hb88e6825_b68da2e0;
        coeff_rom[32] = 64'hb89250ed_b691ce60;
        coeff_rom[33] = 64'hb89654f9_b6961940;
        coeff_rom[34] = 64'hb89a74c1_b69a8420;
        coeff_rom[35] = 64'hb89eb14d_b69f1040;
        coeff_rom[36] = 64'hb8a30b2e_b6a3be60;
        coeff_rom[37] = 64'hb8a78314_b6a88f60;
        coeff_rom[38] = 64'hb8ac1a20_b6ad84a0;
        coeff_rom[39] = 64'hb8b0d0c2_b6b29ec0;
        coeff_rom[40] = 64'hb8b5a839_b6b7df40;
        coeff_rom[41] = 64'hb8baa129_b6bd4700;
        coeff_rom[42] = 64'hb8bfbc5a_b6c2d700;
        coeff_rom[43] = 64'hb8c4fb1d_b6c890e0;
        coeff_rom[44] = 64'hb8ca5ddd_b6ce7540;
        coeff_rom[45] = 64'hb8cfe5ea_b6d485c0;
        coeff_rom[46] = 64'hb8d5943b_b6dac3a0;
        coeff_rom[47] = 64'hb8db69a8_b6e13000;
        coeff_rom[48] = 64'hb8e1677c_b6e7cc80;
        coeff_rom[49] = 64'hb8e78ea8_b6ee9a60;
        coeff_rom[50] = 64'hb8eddfff_b6f59ac0;
        coeff_rom[51] = 64'hb8f45d37_b6fccfc0;
        coeff_rom[52] = 64'hb8fb06e7_b7021d20;
        coeff_rom[53] = 64'hb900ef34_b705ee00;
        coeff_rom[54] = 64'hb90472a8_b709db80;
        coeff_rom[55] = 64'hb9080e40_b70de640;
        coeff_rom[56] = 64'hb90bc28b_b7120f00;
        coeff_rom[57] = 64'hb90f904e_b71656c0;
        coeff_rom[58] = 64'hb913786a_b71abea0;
        coeff_rom[59] = 64'hb9177b13_b71f4700;
        coeff_rom[60] = 64'hb91b997c_b723f160;
        coeff_rom[61] = 64'hb91fd42b_b728be80;
        coeff_rom[62] = 64'hb9242ba8_b72daf20;
        coeff_rom[63] = 64'hb928a102_b732c4a0;
        coeff_rom[64] = 64'hb92d3512_b7380020;
        coeff_rom[65] = 64'hb931e83d_b73d6240;
        coeff_rom[66] = 64'hb936bbc7_b742eca0;
        coeff_rom[67] = 64'hb93bb04a_b748a020;
        coeff_rom[68] = 64'hb940c6b2_b74e7e00;
        coeff_rom[69] = 64'hb945ffea_b7548780;
        coeff_rom[70] = 64'hb94b5cdb_b75abde0;
        coeff_rom[71] = 64'hb950de50_b7612240;
        coeff_rom[72] = 64'hb9568580_b767b640;
        coeff_rom[73] = 64'hb95c5332_b76e7b00;
        coeff_rom[74] = 64'hb962487f_b7757200;
        coeff_rom[75] = 64'hb968667c_b77c9cc0;
        coeff_rom[76] = 64'hb96eae06_b781fe40;
        coeff_rom[77] = 64'hb9752063_b785c980;
        coeff_rom[78] = 64'hb97bbeda_b789b100;
        coeff_rom[79] = 64'hb9814505_b78db540;
        coeff_rom[80] = 64'hb984c1d0_b791d760;
        coeff_rom[81] = 64'hb9885652_b7961820;
        coeff_rom[82] = 64'hb98c030d_b79a7840;
        coeff_rom[83] = 64'hb98fc8ed_b79ef900;
        coeff_rom[84] = 64'hb993a83f_b7a39ae0;
        coeff_rom[85] = 64'hb997a205_b7a85f40;
        coeff_rom[86] = 64'hb99bb688_b7ad46a0;
        coeff_rom[87] = 64'hb99fe6e3_b7b25280;
        coeff_rom[88] = 64'hb9a43377_b7b78380;
        coeff_rom[89] = 64'hb9a89d41_b7bcdb00;
        coeff_rom[90] = 64'hb9ad24ef_b7c25a00;
        coeff_rom[91] = 64'hb9b1cb2a_b7c80180;
        coeff_rom[92] = 64'hb9b690ea_b7cdd2e0;
        coeff_rom[93] = 64'hb9bb76d9_b7d3cf20;
        coeff_rom[94] = 64'hb9c07de9_b7d9f7a0;
        coeff_rom[95] = 64'hb9c5a6f4_b7e04da0;
        coeff_rom[96] = 64'hb9caf29c_b7e6d220;
        coeff_rom[97] = 64'hb9d0621e_b7ed86e0;
        coeff_rom[98] = 64'hb9d5f666_b7f46d40;
        coeff_rom[99] = 64'hb9dbb010_b7fb8640;
        coeff_rom[100] = 64'hb9e19039_b80169c0;
        coeff_rom[101] = 64'hb9e79815_b8052b60;
        coeff_rom[102] = 64'hb9edc83a_b8090880;
        coeff_rom[103] = 64'hb9f4223e_b80d0240;
        coeff_rom[104] = 64'hb9faa6e6_b8111940;
        coeff_rom[105] = 64'hba00ab95_b8154e40;
        coeff_rom[106] = 64'hba041a4a_b819a260;
        coeff_rom[107] = 64'hba079fc0_b81e1600;
        coeff_rom[108] = 64'hba0b3d06_b822aaa0;
        coeff_rom[109] = 64'hba0ef279_b82760e0;
        coeff_rom[110] = 64'hba12c0c2_b82c39c0;
        coeff_rom[111] = 64'hba16a86b_b8313620;
        coeff_rom[112] = 64'hba1aaa4c_b8365740;
        coeff_rom[113] = 64'hba1ec6d5_b83b9de0;
        coeff_rom[114] = 64'hba22fedb_b8410b40;
        coeff_rom[115] = 64'hba275315_b846a080;
        coeff_rom[116] = 64'hba2bc422_b84c5ea0;
        coeff_rom[117] = 64'hba3052cf_b85246e0;
        coeff_rom[118] = 64'hba34ffe9_b8585a80;
        coeff_rom[119] = 64'hba39cc09_b85e9a80;
        coeff_rom[120] = 64'hba3eb829_b8650860;
        coeff_rom[121] = 64'hba43c50f_b86ba560;
        coeff_rom[122] = 64'hba48f34e_b8727280;
        coeff_rom[123] = 64'hba4e440c_b8797180;
        coeff_rom[124] = 64'hba53b850_b8805200;
        coeff_rom[125] = 64'hba59504a_b8840540;
        coeff_rom[126] = 64'hba5f0dd8_b887d3e0;
        coeff_rom[127] = 64'hba64f0f1_b88bbe00;
        coeff_rom[128] = 64'hba6afb71_b88fc500;
        coeff_rom[129] = 64'hba712d7d_b893e920;
        coeff_rom[130] = 64'hba7788e8_b8982bc0;
        coeff_rom[131] = 64'hba7e0e03_b89c8d40;
        coeff_rom[132] = 64'hba825f1f_b8a10ec0;
        coeff_rom[133] = 64'hba85cd51_b8a5b120;
        coeff_rom[134] = 64'hba895234_b8aa7560;
        coeff_rom[135] = 64'hba8cee1d_b8af5c20;
        coeff_rom[136] = 64'hba90a1ea_b8b466c0;
        coeff_rom[137] = 64'hba946dee_b8b995e0;
        coeff_rom[138] = 64'hba98531c_b8beeb00;
        coeff_rom[139] = 64'hba9c51c4_b8c466c0;
        coeff_rom[140] = 64'hbaa06a8e_b8ca0a40;
        coeff_rom[141] = 64'hbaa49e6b_b8cfd700;
        coeff_rom[142] = 64'hbaa8edbd_b8d5cdc0;
        coeff_rom[143] = 64'hbaad5955_b8dbefe0;
        coeff_rom[144] = 64'hbab1e1c1_b8e23e60;
        coeff_rom[145] = 64'hbab687e8_b8e8bac0;
        coeff_rom[146] = 64'hbabb4c80_b8ef6640;
        coeff_rom[147] = 64'hbac03028_b8f64200;
        coeff_rom[148] = 64'hbac533c1_b8fd4f80;
        coeff_rom[149] = 64'hbaca57fc_b9024800;
        coeff_rom[150] = 64'hbacf9de2_b90602a0;
        coeff_rom[151] = 64'hbad505f4_b909d820;
        coeff_rom[152] = 64'hbada9163_b90dc980;
        coeff_rom[153] = 64'hbae040ab_b911d740;
        coeff_rom[154] = 64'hbae61526_b9160280;
        coeff_rom[155] = 64'hbaec0f20_b91a4ba0;
        coeff_rom[156] = 64'hbaf23046_b91eb400;
        coeff_rom[157] = 64'hbaf878b2_b9233be0;
        coeff_rom[158] = 64'hbafeea38_b927e4c0;
        coeff_rom[159] = 64'hbb02c2a3_b92caf20;
        coeff_rom[160] = 64'hbb06257d_b9319c00;
        coeff_rom[161] = 64'hbb099e37_b936ac60;
        coeff_rom[162] = 64'hbb0d2d72_b93be160;
        coeff_rom[163] = 64'hbb10d38c_b9413bc0;
        coeff_rom[164] = 64'hbb149139_b946bcc0;
        coeff_rom[165] = 64'hbb1866ed_b94c6540;
        coeff_rom[166] = 64'hbb1c556a_b95236a0;
        coeff_rom[167] = 64'hbb205d0c_b95831a0;
        coeff_rom[168] = 64'hbb247e95_b95e57a0;
        coeff_rom[169] = 64'hbb28baae_b964a9e0;
        coeff_rom[170] = 64'hbb2d11d8_b96b2960;
        coeff_rom[171] = 64'hbb3184fb_b971d7c0;
        coeff_rom[172] = 64'hbb361468_b978b5c0;
        coeff_rom[173] = 64'hbb3ac12b_b97fc540;
        coeff_rom[174] = 64'hbb3f8b92_b9838380;
        coeff_rom[175] = 64'hbb4474bd_b9873e80;
        coeff_rom[176] = 64'hbb497d1f_b98b1420;
        coeff_rom[177] = 64'hbb4ea5a8_b98f0540;
        coeff_rom[178] = 64'hbb53ef1c_b99312a0;
        coeff_rom[179] = 64'hbb5959e7_b9973cc0;
        coeff_rom[180] = 64'hbb5ee747_b99b84c0;
        coeff_rom[181] = 64'hbb6497cf_b99feb40;
        coeff_rom[182] = 64'hbb6a6c8a_b9a47140;
        coeff_rom[183] = 64'hbb706633_b9a91780;
        coeff_rom[184] = 64'hbb7685a6_b9addee0;
        coeff_rom[185] = 64'hbb7ccbc0_b9b2c840;
        coeff_rom[186] = 64'hbb819cc1_b9b7d4a0;
        coeff_rom[187] = 64'hbb84e7e1_b9bd04e0;
        coeff_rom[188] = 64'hbb8847d4_b9c25a20;
        coeff_rom[189] = 64'hbb8bbd01_b9c7d540;
        coeff_rom[190] = 64'hbb8f47f6_b9cd7760;
        coeff_rom[191] = 64'hbb92e91c_b9d34160;
        coeff_rom[192] = 64'hbb96a110_b9d93480;
        coeff_rom[193] = 64'hbb9a705d_b9df51e0;
        coeff_rom[194] = 64'hbb9e57a0_b9e59ac0;
        coeff_rom[195] = 64'hbba25710_b9ec0fc0;
        coeff_rom[196] = 64'hbba66faa_b9f2b2c0;
        coeff_rom[197] = 64'hbbaaa1b7_b9f98480;
        coeff_rom[198] = 64'hbbaeee18_ba004360;
        coeff_rom[199] = 64'hbbb3553a_ba03dd40;
        coeff_rom[200] = 64'hbbb7d7b0_ba079080;
        coeff_rom[201] = 64'hbbbc7630_ba0b5de0;
        coeff_rom[202] = 64'hbbc1316e_ba0f4620;
        coeff_rom[203] = 64'hbbc609ce_ba1349c0;
        coeff_rom[204] = 64'hbbcb0075_ba1769e0;
        coeff_rom[205] = 64'hbbd015c2_ba1ba700;
        coeff_rom[206] = 64'hbbd54a62_ba2001e0;
        coeff_rom[207] = 64'hbbda9f4a_ba247b80;
        coeff_rom[208] = 64'hbbe014d3_ba291460;
        coeff_rom[209] = 64'hbbe5ac3b_ba2dcdc0;
        coeff_rom[210] = 64'hbbeb65d9_ba32a820;
        coeff_rom[211] = 64'hbbf14295_ba37a480;
        coeff_rom[212] = 64'hbbf74380_ba3cc400;
        coeff_rom[213] = 64'hbbfd6931_ba420760;
        coeff_rom[214] = 64'hbc01da21_ba476f60;
        coeff_rom[215] = 64'hbc0512ff_ba4cfd60;
        coeff_rom[216] = 64'hbc085f7e_ba52b220;
        coeff_rom[217] = 64'hbc0bc01c_ba588ec0;
        coeff_rom[218] = 64'hbc0f3545_ba5e9440;
        coeff_rom[219] = 64'hbc12bf74_ba64c3c0;
        coeff_rom[220] = 64'hbc165f35_ba6b1e80;
        coeff_rom[221] = 64'hbc1a14cc_ba71a540;
        coeff_rom[222] = 64'hbc1de0e4_ba785980;
        coeff_rom[223] = 64'hbc21c405_ba7f3c80;
        coeff_rom[224] = 64'hbc25be91_ba8327a0;
        coeff_rom[225] = 64'hbc29d10b_ba86c980;
        coeff_rom[226] = 64'hbc2dfc19_ba8a84a0;
        coeff_rom[227] = 64'hbc32405e_ba8e59c0;
        coeff_rom[228] = 64'hbc369ded_ba924920;
        coeff_rom[229] = 64'hbc3b15cf_ba9653e0;
        coeff_rom[230] = 64'hbc3fa87e_ba9a7aa0;
        coeff_rom[231] = 64'hbc445695_ba9ebe20;
        coeff_rom[232] = 64'hbc492044_baa31ec0;
        coeff_rom[233] = 64'hbc4e06d0_baa79de0;
        coeff_rom[234] = 64'hbc530a64_baac3be0;
        coeff_rom[235] = 64'hbc582bd8_bab0f9c0;
        coeff_rom[236] = 64'hbc5d6b75_bab5d800;
        coeff_rom[237] = 64'hbc62ca75_babad800;
        coeff_rom[238] = 64'hbc6848fb_babffa20;
        coeff_rom[239] = 64'hbc6de819_bac53fa0;
        coeff_rom[240] = 64'hbc73a830_bacaa920;
        coeff_rom[241] = 64'hbc798a2c_bad037c0;
        coeff_rom[242] = 64'hbc7f8ece_bad5ec80;
        coeff_rom[243] = 64'hbc82db3a_badbc800;
        coeff_rom[244] = 64'hbc860141_bae1cbe0;
        coeff_rom[245] = 64'hbc893965_bae7f840;
        coeff_rom[246] = 64'hbc8c8498_baee4f40;
        coeff_rom[247] = 64'hbc8fe2e1_baf4d140;
        coeff_rom[248] = 64'hbc935499_bafb7f40;
        coeff_rom[249] = 64'hbc96da7a_bb012d80;
        coeff_rom[250] = 64'hbc9a74b9_bb04b2a0;
        coeff_rom[251] = 64'hbc9e23aa_bb084f80;
        coeff_rom[252] = 64'hbca1e7e0_bb0c04e0;
        coeff_rom[253] = 64'hbca5c1ea_bb0fd380;
        coeff_rom[254] = 64'hbca9b1db_bb13bba0;
        coeff_rom[255] = 64'hbcadb89e_bb17be60;
        coeff_rom[256] = 64'hbcb1d63e_bb1bdc00;
        coeff_rom[257] = 64'hbcb60b65_bb201560;
        coeff_rom[258] = 64'hbcba5899_bb246b40;
        coeff_rom[259] = 64'hbcbebe40_bb28de40;
        coeff_rom[260] = 64'hbcc33cdd_bb2d6f20;
        coeff_rom[261] = 64'hbcc7d4d0_bb321e80;
        coeff_rom[262] = 64'hbccc86d6_bb36ed60;
        coeff_rom[263] = 64'hbcd1536c_bb3bdc80;
        coeff_rom[264] = 64'hbcd63acd_bb40ec60;
        coeff_rom[265] = 64'hbcdb3dce_bb461e20;
        coeff_rom[266] = 64'hbce05d01_bb4b72a0;
        coeff_rom[267] = 64'hbce5989b_bb50ea60;
        coeff_rom[268] = 64'hbceaf188_bb5686a0;
        coeff_rom[269] = 64'hbcf06834_bb5c4820;
        coeff_rom[270] = 64'hbcf5fd2a_bb622fc0;
        coeff_rom[271] = 64'hbcfbb10c_bb683e80;
        coeff_rom[272] = 64'hbd00c230_bb6e7540;
        coeff_rom[273] = 64'hbd03bbe2_bb74d500;
        coeff_rom[274] = 64'hbd06c608_bb7b5f00;
        coeff_rom[275] = 64'hbd09e0b4_bb8109e0;
        coeff_rom[276] = 64'hbd0d0c87_bb847a80;
        coeff_rom[277] = 64'hbd104956_bb880160;
        coeff_rom[278] = 64'hbd13981a_bb8b9fc0;
        coeff_rom[279] = 64'hbd16f886_bb8f5580;
        coeff_rom[280] = 64'hbd1a6b70_bb9323c0;
        coeff_rom[281] = 64'hbd1df0c4_bb970aa0;
        coeff_rom[282] = 64'hbd21891a_bb9b0b00;
        coeff_rom[283] = 64'hbd2534cf_bb9f2580;
        coeff_rom[284] = 64'hbd28f403_bba35a80;
        coeff_rom[285] = 64'hbd2cc72b_bba7aac0;
        coeff_rom[286] = 64'hbd30aed8_bbac1720;
        coeff_rom[287] = 64'hbd34ab09_bbb09fe0;
        coeff_rom[288] = 64'hbd38bc49_bbb545e0;
        coeff_rom[289] = 64'hbd3ce321_bbba0a00;
        coeff_rom[290] = 64'hbd411f8c_bbbeec80;
        coeff_rom[291] = 64'hbd45722a_bbc3ee60;
        coeff_rom[292] = 64'hbd49db7e_bbc91080;
        coeff_rom[293] = 64'hbd4e5bb3_bbce5360;
        coeff_rom[294] = 64'hbd52f312_bbd3b7a0;
        coeff_rom[295] = 64'hbd57a24a_bbd93e60;
        coeff_rom[296] = 64'hbd5c696a_bbdee800;
        coeff_rom[297] = 64'hbd614936_bbe4b5c0;
        coeff_rom[298] = 64'hbd6641ee_bbeaa840;
        coeff_rom[299] = 64'hbd6b53b0_bbf0c000;
        coeff_rom[300] = 64'hbd707f72_bbf6fe80;
        coeff_rom[301] = 64'hbd75c51a_bbfd6400;
        coeff_rom[302] = 64'hbd7b2562_bc01f8e0;
        coeff_rom[303] = 64'hbd80504a_bc055440;
        coeff_rom[304] = 64'hbd831b7e_bc08c480;
        coeff_rom[305] = 64'hbd85f4a5_bc0c4a40;
        coeff_rom[306] = 64'hbd88dbdf_bc0fe5e0;
        coeff_rom[307] = 64'hbd8bd169_bc1397e0;
        coeff_rom[308] = 64'hbd8ed562_bc1760a0;
        coeff_rom[309] = 64'hbd91e835_bc1b40e0;
        coeff_rom[310] = 64'hbd9509cc_bc1f38c0;
        coeff_rom[311] = 64'hbd983aa7_bc234920;
        coeff_rom[312] = 64'hbd9b7ae1_bc277260;
        coeff_rom[313] = 64'hbd9ecaac_bc2bb500;
        coeff_rom[314] = 64'hbda22a1e_bc301160;
        coeff_rom[315] = 64'hbda599c9_bc348880;
        coeff_rom[316] = 64'hbda91979_bc391a60;
        coeff_rom[317] = 64'hbdaca9a2_bc3dc7e0;
        coeff_rom[318] = 64'hbdb04a85_bc4291a0;
        coeff_rom[319] = 64'hbdb3fc1b_bc4777e0;
        coeff_rom[320] = 64'hbdb7beeb_bc4c7ba0;
        coeff_rom[321] = 64'hbdbb92d2_bc519d00;
        coeff_rom[322] = 64'hbdbf7852_bc56dd00;
        coeff_rom[323] = 64'hbdc36f46_bc5c3bc0;
        coeff_rom[324] = 64'hbdc7785a_bc61ba80;
        coeff_rom[325] = 64'hbdcb937f_bc675980;
        coeff_rom[326] = 64'hbdcfc0d0_bc6d1940;
        coeff_rom[327] = 64'hbdd40098_bc72fa80;
        coeff_rom[328] = 64'hbdd852ee_bc78fdc0;
        coeff_rom[329] = 64'hbddcb846_bc7f2400;
        coeff_rom[330] = 64'hbde130b4_bc82b6e0;
        coeff_rom[331] = 64'hbde5bc20_bc85eda0;
        coeff_rom[332] = 64'hbdea5b22_bc8936e0;
        coeff_rom[333] = 64'hbdef0d9d_bc8c92c0;
        coeff_rom[334] = 64'hbdf3d3f9_bc9001c0;
        coeff_rom[335] = 64'hbdf8adea_bc9383e0;
        coeff_rom[336] = 64'hbdfd9c2a_bc9719e0;
        coeff_rom[337] = 64'hbe014f35_bc9ac3c0;
        coeff_rom[338] = 64'hbe03da84_bc9e8200;
        coeff_rom[339] = 64'hbe067031_bca25520;
        coeff_rom[340] = 64'hbe090ffc_bca63d00;
        coeff_rom[341] = 64'hbe0bba3a_bcaa3a60;
        coeff_rom[342] = 64'hbe0e6ed9_bcae4d60;
        coeff_rom[343] = 64'hbe112dff_bcb27680;
        coeff_rom[344] = 64'hbe13f796_bcb6b5e0;
        coeff_rom[345] = 64'hbe16cbb0_bcbb0be0;
        coeff_rom[346] = 64'hbe19aa88_bcbf7920;
        coeff_rom[347] = 64'hbe1c93ee_bcc3fda0;
        coeff_rom[348] = 64'hbe1f87dd_bcc899a0;
        coeff_rom[349] = 64'hbe2286a3_bccd4de0;
        coeff_rom[350] = 64'hbe258ff7_bcd21a40;
        coeff_rom[351] = 64'hbe28a3d4_bcd6ff00;
        coeff_rom[352] = 64'hbe2bc2bc_bcdbfd40;
        coeff_rom[353] = 64'hbe2eec05_bce11440;
        coeff_rom[354] = 64'hbe32201c_bce64500;
        coeff_rom[355] = 64'hbe355ea4_bceb8f40;
        coeff_rom[356] = 64'hbe38a7e3_bcf0f3c0;
        coeff_rom[357] = 64'hbe3bfbc8_bcf672c0;
        coeff_rom[358] = 64'hbe3f59d2_bcfc0bc0;
        coeff_rom[359] = 64'hbe42c2b2_bd00e020;
        coeff_rom[360] = 64'hbe46359a_bd03c7a0;
        coeff_rom[361] = 64'hbe49b2ec_bd06bce0;
        coeff_rom[362] = 64'hbe4d3a6f_bd09bfe0;
        coeff_rom[363] = 64'hbe50cbef_bd0cd0a0;
        coeff_rom[364] = 64'hbe54677d_bd0fef60;
        coeff_rom[365] = 64'hbe580cbd_bd131c00;
        coeff_rom[366] = 64'hbe5bbbc0_bd1656c0;
        coeff_rom[367] = 64'hbe5f742a_bd199f80;
        coeff_rom[368] = 64'hbe63360a_bd1cf680;
        coeff_rom[369] = 64'hbe670104_bd205ba0;
        coeff_rom[370] = 64'hbe6ad502_bd23cf00;
        coeff_rom[371] = 64'hbe6eb186_bd275060;
        coeff_rom[372] = 64'hbe7296e2_bd2ae040;
        coeff_rom[373] = 64'hbe76840e_bd2e7de0;
        coeff_rom[374] = 64'hbe7a79a1_bd322a00;
        coeff_rom[375] = 64'hbe7e76b5_bd35e400;
        coeff_rom[376] = 64'hbe813d89_bd39abe0;
        coeff_rom[377] = 64'hbe834352_bd3d81c0;
        coeff_rom[378] = 64'hbe854c89_bd416580;
        coeff_rom[379] = 64'hbe8758be_bd455680;
        coeff_rom[380] = 64'hbe896819_bd495540;
        coeff_rom[381] = 64'hbe8b7a1c_bd4d6100;
        coeff_rom[382] = 64'hbe8d8eef_bd517a40;
        coeff_rom[383] = 64'hbe8fa5d4_bd559fc0;
        coeff_rom[384] = 64'hbe91bef4_bd59d200;
        coeff_rom[385] = 64'hbe93d9f6_bd5e1080;
        coeff_rom[386] = 64'hbe95f681_bd625ac0;
        coeff_rom[387] = 64'hbe981480_bd66b0c0;
        coeff_rom[388] = 64'hbe9a335c_bd6b1180;
        coeff_rom[389] = 64'hbe9c5322_bd6f7d40;
        coeff_rom[390] = 64'hbe9e7320_bd73f2c0;
        coeff_rom[391] = 64'hbea09382_bd787280;
        coeff_rom[392] = 64'hbea2b360_bd7cfac0;
        coeff_rom[393] = 64'hbea4d2e5_bd80c600;
        coeff_rom[394] = 64'hbea6f14e_bd831260;
        coeff_rom[395] = 64'hbea90e50_bd856240;
        coeff_rom[396] = 64'hbeab29c2_bd87b580;
        coeff_rom[397] = 64'hbead4306_bd8a0b80;
        coeff_rom[398] = 64'hbeaf5983_bd8c63a0;
        coeff_rom[399] = 64'hbeb16d4c_bd8ebe00;
        coeff_rom[400] = 64'hbeb37d40_bd911960;
        coeff_rom[401] = 64'hbeb58976_bd9375e0;
        coeff_rom[402] = 64'hbeb7912c_bd95d2a0;
        coeff_rom[403] = 64'hbeb993f0_bd982f20;
        coeff_rom[404] = 64'hbebb9140_bd9a8ac0;
        coeff_rom[405] = 64'hbebd887b_bd9ce4c0;
        coeff_rom[406] = 64'hbebf7926_bd9f3c80;
        coeff_rom[407] = 64'hbec162c6_bda19160;
        coeff_rom[408] = 64'hbec3447c_bda3e240;
        coeff_rom[409] = 64'hbec51df2_bda62ea0;
        coeff_rom[410] = 64'hbec6ee9f_bda875c0;
        coeff_rom[411] = 64'hbec8b584_bdaab640;
        coeff_rom[412] = 64'hbeca723e_bdacef80;
        coeff_rom[413] = 64'hbecc2424_bdaf2080;
        coeff_rom[414] = 64'hbecdca93_bdb14840;
        coeff_rom[415] = 64'hbecf645c_bdb36500;
        coeff_rom[416] = 64'hbed0f1ac_bdb576c0;
        coeff_rom[417] = 64'hbed27104_bdb77b40;
        coeff_rom[418] = 64'hbed3e20a_bdb971c0;
        coeff_rom[419] = 64'hbed543e0_bdbb58c0;
        coeff_rom[420] = 64'hbed695de_bdbd2f00;
        coeff_rom[421] = 64'hbed7d736_bdbef300;
        coeff_rom[422] = 64'hbed90750_bdc0a380;
        coeff_rom[423] = 64'hbeda24e8_bdc23e40;
        coeff_rom[424] = 64'hbedb2fa9_bdc3c240;
        coeff_rom[425] = 64'hbedc26ba_bdc52dc0;
        coeff_rom[426] = 64'hbedd0951_bdc67f00;
        coeff_rom[427] = 64'hbeddd659_bdc7b3c0;
        coeff_rom[428] = 64'hbede8d70_bdc8cac0;
        coeff_rom[429] = 64'hbedf2d48_bdc9c140;
        coeff_rom[430] = 64'hbedfb5e4_bdca9680;
        coeff_rom[431] = 64'hbee02596_bdcb4700;
        coeff_rom[432] = 64'hbee07c26_bdcbd180;
        coeff_rom[433] = 64'hbee0b87a_bdcc3340;
        coeff_rom[434] = 64'hbee0da4c_bdcc6ac0;
        coeff_rom[435] = 64'hbee0e050_bdcc74c0;
        coeff_rom[436] = 64'hbee0ca0c_bdcc4f40;
        coeff_rom[437] = 64'hbee096c7_bdcbf7c0;
        coeff_rom[438] = 64'hbee045b2_bdcb6b80;
        coeff_rom[439] = 64'hbedfd658_bdcaa840;
        coeff_rom[440] = 64'hbedf47e4_bdc9ab00;
        coeff_rom[441] = 64'hbede9994_bdc870c0;
        coeff_rom[442] = 64'hbeddcb45_bdc6f780;
        coeff_rom[443] = 64'hbedcdc10_bdc53bc0;
        coeff_rom[444] = 64'hbedbcb66_bdc33a80;
        coeff_rom[445] = 64'hbeda98ec_bdc0f100;
        coeff_rom[446] = 64'hbed9445a_bdbe5c80;
        coeff_rom[447] = 64'hbed7cd14_bdbb7980;
        coeff_rom[448] = 64'hbed632d4_bdb84500;
        coeff_rom[449] = 64'hbed47566_bdb4bc00;
        coeff_rom[450] = 64'hbed2946a_bdb0db00;
        coeff_rom[451] = 64'hbed08fd2_bdac9f00;
        coeff_rom[452] = 64'hbece6784_bda804c0;
        coeff_rom[453] = 64'hbecc1bb5_bda30980;
        coeff_rom[454] = 64'hbec9abfb_bd9da900;
        coeff_rom[455] = 64'hbec71879_bd97e000;
        coeff_rom[456] = 64'hbec46229_bd91ad00;
        coeff_rom[457] = 64'hbec18856_bd8b0a80;
        coeff_rom[458] = 64'hbebe8be6_bd83f680;
        coeff_rom[459] = 64'hbebb6d61_bd78dc00;
        coeff_rom[460] = 64'hbeb82cf9_bd68da00;
        coeff_rom[461] = 64'hbeb4cb91_bd57e200;
        coeff_rom[462] = 64'hbeb149b7_bd45ed00;
        coeff_rom[463] = 64'hbeada8a1_bd32f700;
        coeff_rom[464] = 64'hbea9e8d1_bd1ef800;
        coeff_rom[465] = 64'hbea60b9d_bd09ec00;
        coeff_rom[466] = 64'hbea211dd_bce79800;
        coeff_rom[467] = 64'hbe9dfd32_bcb92a00;
        coeff_rom[468] = 64'hbe99ce96_bc888000;
        coeff_rom[469] = 64'hbe958799_bc2b2400;
        coeff_rom[470] = 64'hbe9129d7_bb816000;
        coeff_rom[471] = 64'hbe8cb721_3b39a000;
        coeff_rom[472] = 64'hbe8830d9_3c223c00;
        coeff_rom[473] = 64'hbe83990f_3c8d6a00;
        coeff_rom[474] = 64'hbe7de3b2_3ccc1c00;
        coeff_rom[475] = 64'hbe747a12_3d069e00;
        coeff_rom[476] = 64'hbe6af9d2_3d286600;
        coeff_rom[477] = 64'hbe616746_3d4b6800;
        coeff_rom[478] = 64'hbe57c712_3d6fa500;
        coeff_rom[479] = 64'hbe4e1e22_3d8a8e80;
        coeff_rom[480] = 64'hbe4470e2_3d9de900;
        coeff_rom[481] = 64'hbe3ac53e_3db1e000;
        coeff_rom[482] = 64'hbe311fa2_3dc67480;
        coeff_rom[483] = 64'hbe2785e2_3ddba480;
        coeff_rom[484] = 64'hbe1dfd12_3df16f80;
        coeff_rom[485] = 64'hbe148aac_3e03ea00;
        coeff_rom[486] = 64'hbe0b3466_3e0f67e0;
        coeff_rom[487] = 64'hbe01ffa9_3e1b3080;
        coeff_rom[488] = 64'hbdf1e3f2_3e2742c0;
        coeff_rom[489] = 64'hbde02264_3e339ce0;
        coeff_rom[490] = 64'hbdcec55c_3e403da0;
        coeff_rom[491] = 64'hbdbdd7fa_3e4d2340;
        coeff_rom[492] = 64'hbdad655a_3e5a4bc0;
        coeff_rom[493] = 64'hbd9d7812_3e67b540;
        coeff_rom[494] = 64'hbd8e1aee_3e755d60;
        coeff_rom[495] = 64'hbd7eb04c_3e81a0f0;
        coeff_rom[496] = 64'hbd62738c_3e88b020;
        coeff_rom[497] = 64'hbd479378_3e8fdad0;
        coeff_rom[498] = 64'hbd2e21f8_3e971fd0;
        coeff_rom[499] = 64'hbd1631e4_3e9e7d60;
        coeff_rom[500] = 64'hbcffa688_3ea5f240;
        coeff_rom[501] = 64'hbcd62dd0_3ead7c90;
        coeff_rom[502] = 64'hbcb016b8_3eb51ac8;
        coeff_rom[503] = 64'hbc8d7c9c_3ebccb40;
        coeff_rom[504] = 64'hbc5cf278_3ec48c18;
        coeff_rom[505] = 64'hbc2646a0_3ecc5b80;
        coeff_rom[506] = 64'hbbee3b60_3ed437a8;
        coeff_rom[507] = 64'hbb9f3530_3edc1eac;
        coeff_rom[508] = 64'hbb3f6c70_3ee40e8c;
        coeff_rom[509] = 64'hbabfb400_3eec056a;
        coeff_rom[510] = 64'hb9ffda80_3ef40141;
        coeff_rom[511] = 64'h00000000_3efc0015;
        coeff_rom[512] = 64'h00000000_3f01fff5;
        coeff_rom[513] = 64'hb9ffdb00_3f05ff61;
        coeff_rom[514] = 64'hbabfb3e0_3f09fd4a;
        coeff_rom[515] = 64'hbb3f6c40_3f0df8b8;
        coeff_rom[516] = 64'hbb9f3560_3f11f0ac;
        coeff_rom[517] = 64'hbbee3b60_3f15e42c;
        coeff_rom[518] = 64'hbc2646a0_3f19d240;
        coeff_rom[519] = 64'hbc5cf2b0_3f1db9f8;
        coeff_rom[520] = 64'hbc8d7c98_3f219a60;
        coeff_rom[521] = 64'hbcb01690_3f257298;
        coeff_rom[522] = 64'hbcd62dd0_3f2941b8;
        coeff_rom[523] = 64'hbcffa688_3f2d06e0;
        coeff_rom[524] = 64'hbd1631e4_3f30c150;
        coeff_rom[525] = 64'hbd2e21fc_3f347018;
        coeff_rom[526] = 64'hbd479340_3f381290;
        coeff_rom[527] = 64'hbd627408_3f3ba800;
        coeff_rom[528] = 64'hbd7eb008_3f3f2f80;
        coeff_rom[529] = 64'hbd8e1b10_3f42a8b0;
        coeff_rom[530] = 64'hbd9d7810_3f4612b0;
        coeff_rom[531] = 64'hbdad6558_3f496d10;
        coeff_rom[532] = 64'hbdbdd7f8_3f4cb730;
        coeff_rom[533] = 64'hbdcec52c_3f4ff090;
        coeff_rom[534] = 64'hbde02238_3f5318c0;
        coeff_rom[535] = 64'hbdf1e450_3f562f60;
        coeff_rom[536] = 64'hbe01ffa8_3f5933e0;
        coeff_rom[537] = 64'hbe0b344c_3f5c2600;
        coeff_rom[538] = 64'hbe148aac_3f5f0580;
        coeff_rom[539] = 64'hbe1dfcdc_3f61d200;
        coeff_rom[540] = 64'hbe27861c_3f648b80;
        coeff_rom[541] = 64'hbe311fdc_3f673180;
        coeff_rom[542] = 64'hbe3ac4c4_3f69c3e0;
        coeff_rom[543] = 64'hbe447160_3f6c4300;
        coeff_rom[544] = 64'hbe4e1de0_3f6eae20;
        coeff_rom[545] = 64'hbe57c6d0_3f7105a0;
        coeff_rom[546] = 64'hbe616748_3f734980;
        coeff_rom[547] = 64'hbe6af9d8_3f7579a0;
        coeff_rom[548] = 64'hbe747a14_3f779620;
        coeff_rom[549] = 64'hbe7de3b0_3f799f20;
        coeff_rom[550] = 64'hbe839936_3f7b94c0;
        coeff_rom[551] = 64'hbe883102_3f7d7720;
        coeff_rom[552] = 64'hbe8cb6d0_3f7f4640;
        coeff_rom[553] = 64'hbe9129d8_3f808160;
        coeff_rom[554] = 64'hbe958818_3f815660;
        coeff_rom[555] = 64'hbe99cde8_3f8221e0;
        coeff_rom[556] = 64'hbe9dfdb8_3f82e4c0;
        coeff_rom[557] = 64'hbea211dc_3f839e60;
        coeff_rom[558] = 64'hbea60b9c_3f844f60;
        coeff_rom[559] = 64'hbea9e8d0_3f84f7c0;
        coeff_rom[560] = 64'hbeada810_3f8597a0;
        coeff_rom[561] = 64'hbeb14a4c_3f862f80;
        coeff_rom[562] = 64'hbeb4cb2c_3f86bf00;
        coeff_rom[563] = 64'hbeb82d60_3f8746e0;
        coeff_rom[564] = 64'hbebb6d60_3f87c6e0;
        coeff_rom[565] = 64'hbebe8bb0_3f883f60;
        coeff_rom[566] = 64'hbec18820_3f88b0a0;
        coeff_rom[567] = 64'hbec46298_3f891ae0;
        coeff_rom[568] = 64'hbec71878_3f897e00;
        coeff_rom[569] = 64'hbec9ab88_3f89da80;
        coeff_rom[570] = 64'hbecc1bf0_3f8a30a0;
        coeff_rom[571] = 64'hbece672c_3f8a8040;
        coeff_rom[572] = 64'hbed0904c_3f8aca00;
        coeff_rom[573] = 64'hbed293ec_3f8b0da0;
        coeff_rom[574] = 64'hbed47568_3f8b4bc0;
        coeff_rom[575] = 64'hbed63350_3f8b8460;
        coeff_rom[576] = 64'hbed7cd54_3f8bb7a0;
        coeff_rom[577] = 64'hbed94418_3f8be5c0;
        coeff_rom[578] = 64'hbeda9868_3f8c0f00;
        coeff_rom[579] = 64'hbedbcc30_3f8c33c0;
        coeff_rom[580] = 64'hbedcdb20_3f8c53a0;
        coeff_rom[581] = 64'hbeddcb8c_3f8c6f80;
        coeff_rom[582] = 64'hbede9a44_3f8c8720;
        coeff_rom[583] = 64'hbedf4870_3f8c9ac0;
        coeff_rom[584] = 64'hbedfd630_3f8caa80;
        coeff_rom[585] = 64'hbee045f8_3f8cb6c0;
        coeff_rom[586] = 64'hbee09498_3f8cbf40;
        coeff_rom[587] = 64'hbee0ca80_3f8cc500;
        coeff_rom[588] = 64'hbee0dfe0_3f8cc740;
        coeff_rom[589] = 64'hbee0db10_3f8cc6c0;
        coeff_rom[590] = 64'hbee0b8f0_3f8cc340;
        coeff_rom[591] = 64'hbee07b38_3f8cbd00;
        coeff_rom[592] = 64'hbee02638_3f8cb480;
        coeff_rom[593] = 64'hbedfb6d8_3f8ca980;
        coeff_rom[594] = 64'hbedf2c78_3f8c9c00;
        coeff_rom[595] = 64'hbede8e40_3f8c8cc0;
        coeff_rom[596] = 64'hbeddd680_3f8c7b40;
        coeff_rom[597] = 64'hbedd0750_3f8c67c0;
        coeff_rom[598] = 64'hbedc2840_3f8c5300;
        coeff_rom[599] = 64'hbedb2e20_3f8c3c00;
        coeff_rom[600] = 64'hbeda2620_3f8c2400;
        coeff_rom[601] = 64'hbed907a8_3f8c0a40;
        coeff_rom[602] = 64'hbed7d7e8_3f8bef40;
        coeff_rom[603] = 64'hbed693b8_3f8bd2c0;
        coeff_rom[604] = 64'hbed54638_3f8bb5c0;
        coeff_rom[605] = 64'hbed3e0c0_3f8b9700;
        coeff_rom[606] = 64'hbed27190_3f8b77c0;
        coeff_rom[607] = 64'hbed0efa0_3f8b5740;
        coeff_rom[608] = 64'hbecf66a0_3f8b3680;
        coeff_rom[609] = 64'hbecdca60_3f8b1480;
        coeff_rom[610] = 64'hbecc23c0_3f8af200;
        coeff_rom[611] = 64'hbeca72a0_3f8acf00;
        coeff_rom[612] = 64'hbec8b3c0_3f8aab40;
        coeff_rom[613] = 64'hbec6f068_3f8a8780;
        coeff_rom[614] = 64'hbec51bd8_3f8a62c0;
        coeff_rom[615] = 64'hbec345e8_3f8a3e40;
        coeff_rom[616] = 64'hbec161a8_3f8a1900;
        coeff_rom[617] = 64'hbebf78c0_3f89f3c0;
        coeff_rom[618] = 64'hbebd8b30_3f89ce80;
        coeff_rom[619] = 64'hbebb8ef0_3f89a880;
        coeff_rom[620] = 64'hbeb994b0_3f898300;
        coeff_rom[621] = 64'hbeb79258_3f895d40;
        coeff_rom[622] = 64'hbeb587d8_3f893740;
        coeff_rom[623] = 64'hbeb37f88_3f8911c0;
        coeff_rom[624] = 64'hbeb16b88_3f88ebc0;
        coeff_rom[625] = 64'hbeaf59d8_3f88c640;
        coeff_rom[626] = 64'hbead4378_3f88a0c0;
        coeff_rom[627] = 64'hbeab2868_3f887b40;
        coeff_rom[628] = 64'hbea90fe8_3f885640;
        coeff_rom[629] = 64'hbea6ef20_3f883100;
        coeff_rom[630] = 64'hbea4d4c0_3f880c80;
        coeff_rom[631] = 64'hbea2b218_3f87e7c0;
        coeff_rom[632] = 64'hbea09618_3f87c3c0;
        coeff_rom[633] = 64'hbe9e71d0_3f879f80;
        coeff_rom[634] = 64'hbe9c5470_3f877c00;
        coeff_rom[635] = 64'hbe9a32a0_3f875880;
        coeff_rom[636] = 64'hbe981420_3f873580;
        coeff_rom[637] = 64'hbe95f530_3f8712c0;
        coeff_rom[638] = 64'hbe93d9b8_3f86f080;
        coeff_rom[639] = 64'hbe91bdf8_3f86ce80;
        coeff_rom[640] = 64'hbe8fa5f8_3f86ad00;
        coeff_rom[641] = 64'hbe8d91d8_3f868c00;
        coeff_rom[642] = 64'hbe8b7588_3f866ac0;
        coeff_rom[643] = 64'hbe896da0_3f864b00;
        coeff_rom[644] = 64'hbe875560_3f862a80;
        coeff_rom[645] = 64'hbe8549b0_3f860b00;
        coeff_rom[646] = 64'hbe834ad0_3f85ec80;
        coeff_rom[647] = 64'hbe813740_3f85cd00;
        coeff_rom[648] = 64'hbe7e8380_3f85af80;
        coeff_rom[649] = 64'hbe7a6ee0_3f859100;
        coeff_rom[650] = 64'hbe768660_3f857400;
        coeff_rom[651] = 64'hbe7296a0_3f855700;
        coeff_rom[652] = 64'hbe6eb120_3f853a80;
        coeff_rom[653] = 64'hbe6ad620_3f851e80;
        coeff_rom[654] = 64'hbe6705e0_3f850300;
        coeff_rom[655] = 64'hbe632ec0_3f84e780;
        coeff_rom[656] = 64'hbe5f74c0_3f84cd00;
        coeff_rom[657] = 64'hbe5bc640_3f84b300;
        coeff_rom[658] = 64'hbe57ff00_3f849880;
        coeff_rom[659] = 64'hbe546840_3f847f80;
        coeff_rom[660] = 64'hbe50cb40_3f846680;
        coeff_rom[661] = 64'hbe4d3aa0_3f844e00;
        coeff_rom[662] = 64'hbe49b6a0_3f843600;
        coeff_rom[663] = 64'hbe463f80_3f841e80;
        coeff_rom[664] = 64'hbe42c280_3f840700;
        coeff_rom[665] = 64'hbe3f52c0_3f83f000;
        coeff_rom[666] = 64'hbe3c03c0_3f83da00;
        coeff_rom[667] = 64'hbe389be0_3f83c380;
        coeff_rom[668] = 64'hbe3568e0_3f83ae80;
        coeff_rom[669] = 64'hbe321d00_3f839900;
        coeff_rom[670] = 64'hbe2edf80_3f838400;
        coeff_rom[671] = 64'hbe2bc480_3f837000;
        coeff_rom[672] = 64'hbe28a480_3f835c00;
        coeff_rom[673] = 64'hbe2593a0_3f834880;
        coeff_rom[674] = 64'hbe229220_3f833580;
        coeff_rom[675] = 64'hbe1f7780_3f832200;
        coeff_rom[676] = 64'hbe1c9580_3f831000;
        coeff_rom[677] = 64'hbe19af00_3f82fe00;
        coeff_rom[678] = 64'hbe16c400_3f82ec00;
        coeff_rom[679] = 64'hbe13fe40_3f82db00;
        coeff_rom[680] = 64'hbe113440_3f82ca00;
        coeff_rom[681] = 64'hbe0e6600_3f82b900;
        coeff_rom[682] = 64'hbe0bbe00_3f82a900;
        coeff_rom[683] = 64'hbe091200_3f829900;
        coeff_rom[684] = 64'hbe067780_3f828980;
        coeff_rom[685] = 64'hbe03d920_3f827a00;
        coeff_rom[686] = 64'hbe014ca0_3f826b00;
        coeff_rom[687] = 64'hbdfda480_3f825c80;
        coeff_rom[688] = 64'hbdf8a880_3f824e00;
        coeff_rom[689] = 64'hbdf3d180_3f824000;
        coeff_rom[690] = 64'hbdeef380_3f823200;
        coeff_rom[691] = 64'hbdea6800_3f822500;
        coeff_rom[692] = 64'hbde5d600_3f821800;
        coeff_rom[693] = 64'hbde11040_3f820a80;
        coeff_rom[694] = 64'hbddccc40_3f81fe80;
        coeff_rom[695] = 64'hbdd85480_3f81f200;
        coeff_rom[696] = 64'hbdd40480_3f81e600;
        coeff_rom[697] = 64'hbdcfae80_3f81da00;
        coeff_rom[698] = 64'hbdcbaf80_3f81cf00;
        coeff_rom[699] = 64'hbdc74d80_3f81c300;
        coeff_rom[700] = 64'hbdc37280_3f81b880;
        coeff_rom[701] = 64'hbdbf9240_3f81ae00;
        coeff_rom[702] = 64'hbdbb7d40_3f81a300;
        coeff_rom[703] = 64'hbdb7c240_3f819900;
        coeff_rom[704] = 64'hbdb40240_3f818f00;
        coeff_rom[705] = 64'hbdb03d40_3f818500;
        coeff_rom[706] = 64'hbdaca3c0_3f817b80;
        coeff_rom[707] = 64'hbda93640_3f817280;
        coeff_rom[708] = 64'hbda59340_3f816900;
        coeff_rom[709] = 64'hbda21cc0_3f816000;
        coeff_rom[710] = 64'hbd9ed340_3f815780;
        coeff_rom[711] = 64'hbd9b8580_3f814f00;
        coeff_rom[712] = 64'hbd983380_3f814680;
        coeff_rom[713] = 64'hbd950f80_3f813e80;
        coeff_rom[714] = 64'hbd91e780_3f813680;
        coeff_rom[715] = 64'hbd8ebb80_3f812e80;
        coeff_rom[716] = 64'hbd8bf180_3f812780;
        coeff_rom[717] = 64'hbd88bd80_3f811f80;
        coeff_rom[718] = 64'hbd862000_3f811900;
        coeff_rom[719] = 64'hbd8317c0_3f811180;
        coeff_rom[720] = 64'hbd803fc0_3f810a80;
        coeff_rom[721] = 64'hbd7b3100_3f810400;
        coeff_rom[722] = 64'hbd75dc00_3f80fd80;
        coeff_rom[723] = 64'hbd708080_3f80f700;
        coeff_rom[724] = 64'hbd6b1e80_3f80f080;
        coeff_rom[725] = 64'hbd662080_3f80ea80;
        coeff_rom[726] = 64'hbd618780_3f80e500;
        coeff_rom[727] = 64'hbd5c7d80_3f80df00;
        coeff_rom[728] = 64'hbd576d80_3f80d900;
        coeff_rom[729] = 64'hbd533080_3f80d400;
        coeff_rom[730] = 64'hbd4e1480_3f80ce00;
        coeff_rom[731] = 64'hbd49cd80_3f80c900;
        coeff_rom[732] = 64'hbd458180_3f80c400;
        coeff_rom[733] = 64'hbd413080_3f80bf00;
        coeff_rom[734] = 64'hbd3cda80_3f80ba00;
        coeff_rom[735] = 64'hbd38ef00_3f80b580;
        coeff_rom[736] = 64'hbd348f00_3f80b080;
        coeff_rom[737] = 64'hbd309a80_3f80ac00;
        coeff_rom[738] = 64'hbd2ca180_3f80a780;
        coeff_rom[739] = 64'hbd291580_3f80a380;
        coeff_rom[740] = 64'hbd251380_3f809f00;
        coeff_rom[741] = 64'hbd21f200_3f809b80;
        coeff_rom[742] = 64'hbd1de700_3f809700;
        coeff_rom[743] = 64'hbd1a4b00_3f809300;
        coeff_rom[744] = 64'hbd171f00_3f808f80;
        coeff_rom[745] = 64'hbd137b00_3f808b80;
        coeff_rom[746] = 64'hbd104800_3f808800;
        coeff_rom[747] = 64'hbd0d1180_3f808480;
        coeff_rom[748] = 64'hbd09d780_3f808100;
        coeff_rom[749] = 64'hbd069a00_3f807d80;
        coeff_rom[750] = 64'hbd03d000_3f807a80;
        coeff_rom[751] = 64'hbd010300_3f807780;
        coeff_rom[752] = 64'hbcfb7600_3f807400;
        coeff_rom[753] = 64'hbcf5d000_3f807100;
        coeff_rom[754] = 64'hbcf02400_3f806e00;
        coeff_rom[755] = 64'hbceb6500_3f806b80;
        coeff_rom[756] = 64'hbce5ad00_3f806880;
        coeff_rom[757] = 64'hbcdfef00_3f806580;
        coeff_rom[758] = 64'hbcdb2100_3f806300;
        coeff_rom[759] = 64'hbcd64e00_3f806080;
        coeff_rom[760] = 64'hbcd17600_3f805e00;
        coeff_rom[761] = 64'hbccc9900_3f805b80;
        coeff_rom[762] = 64'hbcc7b700_3f805900;
        coeff_rom[763] = 64'hbcc3cb00_3f805700;
        coeff_rom[764] = 64'hbcbde300_3f805400;
        coeff_rom[765] = 64'hbcbaec00_3f805280;
        coeff_rom[766] = 64'hbcb5f600_3f805000;
        coeff_rom[767] = 64'hbcb1fa00_3f804e00;
        coeff_rom[768] = 64'hbcadfa00_3f804c00;
        coeff_rom[769] = 64'hbca9f600_3f804a00;
        coeff_rom[770] = 64'hbca5ee00_3f804800;
        coeff_rom[771] = 64'hbca1e200_3f804600;
        coeff_rom[772] = 64'hbc9dd200_3f804400;
        coeff_rom[773] = 64'hbc99be00_3f804200;
        coeff_rom[774] = 64'hbc97b200_3f804100;
        coeff_rom[775] = 64'hbc939600_3f803f00;
        coeff_rom[776] = 64'hbc8f7600_3f803d00;
        coeff_rom[777] = 64'hbc8b5200_3f803b00;
        coeff_rom[778] = 64'hbc893e00_3f803a00;
        coeff_rom[779] = 64'hbc872800_3f803900;
        coeff_rom[780] = 64'hbc82f800_3f803700;
        coeff_rom[781] = 64'hbc7d8800_3f803500;
        coeff_rom[782] = 64'hbc795000_3f803400;
        coeff_rom[783] = 64'hbc751400_3f803300;
        coeff_rom[784] = 64'hbc6c9400_3f803100;
        coeff_rom[785] = 64'hbc685000_3f803000;
        coeff_rom[786] = 64'hbc640800_3f802f00;
        coeff_rom[787] = 64'hbc5b7000_3f802d00;
        coeff_rom[788] = 64'hbc5b7000_3f802d00;
        coeff_rom[789] = 64'hbc52c800_3f802b00;
        coeff_rom[790] = 64'hbc4e7000_3f802a00;
        coeff_rom[791] = 64'hbc45b800_3f802800;
        coeff_rom[792] = 64'hbc45b800_3f802800;
        coeff_rom[793] = 64'hbc415400_3f802700;
        coeff_rom[794] = 64'hbc388400_3f802500;
        coeff_rom[795] = 64'hbc388400_3f802500;
        coeff_rom[796] = 64'hbc2fa400_3f802300;
        coeff_rom[797] = 64'hbc2fa400_3f802300;
        coeff_rom[798] = 64'hbc2b2c00_3f802200;
        coeff_rom[799] = 64'hbc26b000_3f802100;
        coeff_rom[800] = 64'hbc1db000_3f801f00;
        coeff_rom[801] = 64'hbc1db000_3f801f00;
        coeff_rom[802] = 64'hbc1db000_3f801f00;
        coeff_rom[803] = 64'hbc149800_3f801d00;
        coeff_rom[804] = 64'hbc149800_3f801d00;
        coeff_rom[805] = 64'hbc0b7000_3f801b00;
        coeff_rom[806] = 64'hbc100800_3f801c00;
        coeff_rom[807] = 64'hbc06d000_3f801a00;
        coeff_rom[808] = 64'hbc023000_3f801900;
        coeff_rom[809] = 64'hbc023000_3f801900;
        coeff_rom[810] = 64'hbc023000_3f801900;
        coeff_rom[811] = 64'hbbf1b000_3f801700;
        coeff_rom[812] = 64'hbbf1b000_3f801700;
        coeff_rom[813] = 64'hbbf1b000_3f801700;
        coeff_rom[814] = 64'hbbded000_3f801500;
        coeff_rom[815] = 64'hbbded000_3f801500;
        coeff_rom[816] = 64'hbbded000_3f801500;
        coeff_rom[817] = 64'hbbd54800_3f801400;
        coeff_rom[818] = 64'hbbcbb800_3f801300;
        coeff_rom[819] = 64'hbbcbb800_3f801300;
        coeff_rom[820] = 64'hbbcbb800_3f801300;
        coeff_rom[821] = 64'hbbc21000_3f801200;
        coeff_rom[822] = 64'hbbb86000_3f801100;
        coeff_rom[823] = 64'hbbb86000_3f801100;
        coeff_rom[824] = 64'hbbb86000_3f801100;
        coeff_rom[825] = 64'hbbae9800_3f801000;
        coeff_rom[826] = 64'hbba4c800_3f800f00;
        coeff_rom[827] = 64'hbba4c800_3f800f00;
        coeff_rom[828] = 64'hbba4c800_3f800f00;
        coeff_rom[829] = 64'hbb9ae000_3f800e00;
        coeff_rom[830] = 64'hbb9ae000_3f800e00;
        coeff_rom[831] = 64'hbb9ae000_3f800e00;
        coeff_rom[832] = 64'hbb90e000_3f800d00;
        coeff_rom[833] = 64'hbb90e000_3f800d00;
        coeff_rom[834] = 64'hbb90e000_3f800d00;
        coeff_rom[835] = 64'hbb86c800_3f800c00;
        coeff_rom[836] = 64'hbb795000_3f800b00;
        coeff_rom[837] = 64'hbb86d000_3f800c00;
        coeff_rom[838] = 64'hbb794000_3f800b00;
        coeff_rom[839] = 64'hbb794000_3f800b00;
        coeff_rom[840] = 64'hbb794000_3f800b00;
        coeff_rom[841] = 64'hbb64b000_3f800a00;
        coeff_rom[842] = 64'hbb64b000_3f800a00;
        coeff_rom[843] = 64'hbb64b000_3f800a00;
        coeff_rom[844] = 64'hbb4ff000_3f800900;
        coeff_rom[845] = 64'hbb4ff000_3f800900;
        coeff_rom[846] = 64'hbb4ff000_3f800900;
        coeff_rom[847] = 64'hbb4ff000_3f800900;
        coeff_rom[848] = 64'hbb3af000_3f800800;
        coeff_rom[849] = 64'hbb500000_3f800900;
        coeff_rom[850] = 64'hbb25c000_3f800700;
        coeff_rom[851] = 64'hbb3af000_3f800800;
        coeff_rom[852] = 64'hbb3af000_3f800800;
        coeff_rom[853] = 64'hbb25a000_3f800700;
        coeff_rom[854] = 64'hbb25a000_3f800700;
        coeff_rom[855] = 64'hbb25a000_3f800700;
        coeff_rom[856] = 64'hbb25a000_3f800700;
        coeff_rom[857] = 64'hbb25a000_3f800700;
        coeff_rom[858] = 64'hbb100000_3f800600;
        coeff_rom[859] = 64'hbb100000_3f800600;
        coeff_rom[860] = 64'hbb100000_3f800600;
        coeff_rom[861] = 64'hbb100000_3f800600;
        coeff_rom[862] = 64'hbb100000_3f800600;
        coeff_rom[863] = 64'hbaf42000_3f800500;
        coeff_rom[864] = 64'hbb101000_3f800600;
        coeff_rom[865] = 64'hbaf40000_3f800500;
        coeff_rom[866] = 64'hbaf40000_3f800500;
        coeff_rom[867] = 64'hbaf40000_3f800500;
        coeff_rom[868] = 64'hbaf40000_3f800500;
        coeff_rom[869] = 64'hbaf40000_3f800500;
        coeff_rom[870] = 64'hbac74000_3f800400;
        coeff_rom[871] = 64'hbaf42000_3f800500;
        coeff_rom[872] = 64'hbac72000_3f800400;
        coeff_rom[873] = 64'hbac72000_3f800400;
        coeff_rom[874] = 64'hbac72000_3f800400;
        coeff_rom[875] = 64'hbac72000_3f800400;
        coeff_rom[876] = 64'hbac72000_3f800400;
        coeff_rom[877] = 64'hbac72000_3f800400;
        coeff_rom[878] = 64'hba996000_3f800300;
        coeff_rom[879] = 64'hbac74000_3f800400;
        coeff_rom[880] = 64'hba994000_3f800300;
        coeff_rom[881] = 64'hbac76000_3f800400;
        coeff_rom[882] = 64'hba992000_3f800300;
        coeff_rom[883] = 64'hba992000_3f800300;
        coeff_rom[884] = 64'hba992000_3f800300;
        coeff_rom[885] = 64'hba992000_3f800300;
        coeff_rom[886] = 64'hba992000_3f800300;
        coeff_rom[887] = 64'hba992000_3f800300;
        coeff_rom[888] = 64'hba992000_3f800300;
        coeff_rom[889] = 64'hba540000_3f800200;
        coeff_rom[890] = 64'hba994000_3f800300;
        coeff_rom[891] = 64'hba53c000_3f800200;
        coeff_rom[892] = 64'hba996000_3f800300;
        coeff_rom[893] = 64'hba538000_3f800200;
        coeff_rom[894] = 64'hba538000_3f800200;
        coeff_rom[895] = 64'hba99a000_3f800300;
        coeff_rom[896] = 64'hba534000_3f800200;
        coeff_rom[897] = 64'hba534000_3f800200;
        coeff_rom[898] = 64'hba534000_3f800200;
        coeff_rom[899] = 64'hba534000_3f800200;
        coeff_rom[900] = 64'hba534000_3f800200;
        coeff_rom[901] = 64'hba534000_3f800200;
        coeff_rom[902] = 64'hba534000_3f800200;
        coeff_rom[903] = 64'hba534000_3f800200;
        coeff_rom[904] = 64'hb9e28000_3f800100;
        coeff_rom[905] = 64'hba538000_3f800200;
        coeff_rom[906] = 64'hba538000_3f800200;
        coeff_rom[907] = 64'hb9e18000_3f800100;
        coeff_rom[908] = 64'hba53c000_3f800200;
        coeff_rom[909] = 64'hb9e10000_3f800100;
        coeff_rom[910] = 64'hba540000_3f800200;
        coeff_rom[911] = 64'hb9e08000_3f800100;
        coeff_rom[912] = 64'hba544000_3f800200;
        coeff_rom[913] = 64'hb9e00000_3f800100;
        coeff_rom[914] = 64'hb9e00000_3f800100;
        coeff_rom[915] = 64'hb9e00000_3f800100;
        coeff_rom[916] = 64'hba550000_3f800200;
        coeff_rom[917] = 64'hb9df8000_3f800100;
        coeff_rom[918] = 64'hb9df8000_3f800100;
        coeff_rom[919] = 64'hb9df8000_3f800100;
        coeff_rom[920] = 64'hb9df8000_3f800100;
        coeff_rom[921] = 64'hb9df8000_3f800100;
        coeff_rom[922] = 64'hb9df8000_3f800100;
        coeff_rom[923] = 64'hb9df8000_3f800100;
        coeff_rom[924] = 64'hb9df8000_3f800100;
        coeff_rom[925] = 64'hb9df8000_3f800100;
        coeff_rom[926] = 64'hb9df8000_3f800100;
        coeff_rom[927] = 64'hb9df8000_3f800100;
        coeff_rom[928] = 64'hb9df8000_3f800100;
        coeff_rom[929] = 64'hb9df8000_3f800100;
        coeff_rom[930] = 64'hb9df8000_3f800100;
        coeff_rom[931] = 64'hb9df8000_3f800100;
        coeff_rom[932] = 64'hb7d80000_3f800000;
        coeff_rom[933] = 64'hb9e00000_3f800100;
        coeff_rom[934] = 64'hb9e00000_3f800100;
        coeff_rom[935] = 64'hb9e00000_3f800100;
        coeff_rom[936] = 64'hb7c00000_3f800000;
        coeff_rom[937] = 64'hb9e08000_3f800100;
        coeff_rom[938] = 64'hb9e08000_3f800100;
        coeff_rom[939] = 64'hb7b00000_3f800000;
        coeff_rom[940] = 64'hb9e10000_3f800100;
        coeff_rom[941] = 64'hb7a80000_3f800000;
        coeff_rom[942] = 64'hb9e18000_3f800100;
        coeff_rom[943] = 64'hb9e18000_3f800100;
        coeff_rom[944] = 64'hb7980000_3f800000;
        coeff_rom[945] = 64'hb9e20000_3f800100;
        coeff_rom[946] = 64'hb7900000_3f800000;
        coeff_rom[947] = 64'hb9e28000_3f800100;
        coeff_rom[948] = 64'hb7880000_3f800000;
        coeff_rom[949] = 64'hb9e30000_3f800100;
        coeff_rom[950] = 64'hb7800000_3f800000;
        coeff_rom[951] = 64'hb9e38000_3f800100;
        coeff_rom[952] = 64'hb7700000_3f800000;
        coeff_rom[953] = 64'hb7700000_3f800000;
        coeff_rom[954] = 64'hb9e48000_3f800100;
        coeff_rom[955] = 64'hb7600000_3f800000;
        coeff_rom[956] = 64'hb9e50000_3f800100;
        coeff_rom[957] = 64'hb7500000_3f800000;
        coeff_rom[958] = 64'hb7500000_3f800000;
        coeff_rom[959] = 64'hb9e60000_3f800100;
        coeff_rom[960] = 64'hb7400000_3f800000;
        coeff_rom[961] = 64'hb7400000_3f800000;
        coeff_rom[962] = 64'hb9e70000_3f800100;
        coeff_rom[963] = 64'hb7300000_3f800000;
        coeff_rom[964] = 64'hb7300000_3f800000;
        coeff_rom[965] = 64'hb9e80000_3f800100;
        coeff_rom[966] = 64'hb7200000_3f800000;
        coeff_rom[967] = 64'hb7200000_3f800000;
        coeff_rom[968] = 64'hb9e90000_3f800100;
        coeff_rom[969] = 64'hb7100000_3f800000;
        coeff_rom[970] = 64'hb7100000_3f800000;
        coeff_rom[971] = 64'hb7100000_3f800000;
        coeff_rom[972] = 64'hb9ea8000_3f800100;
        coeff_rom[973] = 64'hb7000000_3f800000;
        coeff_rom[974] = 64'hb7000000_3f800000;
        coeff_rom[975] = 64'hb7000000_3f800000;
        coeff_rom[976] = 64'hb9ec0000_3f800100;
        coeff_rom[977] = 64'hb6e00000_3f800000;
        coeff_rom[978] = 64'hb6e00000_3f800000;
        coeff_rom[979] = 64'hb6e00000_3f800000;
        coeff_rom[980] = 64'hb6e00000_3f800000;
        coeff_rom[981] = 64'hb9ee0000_3f800100;
        coeff_rom[982] = 64'hb6c00000_3f800000;
        coeff_rom[983] = 64'hb6c00000_3f800000;
        coeff_rom[984] = 64'hb6c00000_3f800000;
        coeff_rom[985] = 64'hb6c00000_3f800000;
        coeff_rom[986] = 64'hb6c00000_3f800000;
        coeff_rom[987] = 64'hb9f08000_3f800100;
        coeff_rom[988] = 64'hb6a00000_3f800000;
        coeff_rom[989] = 64'hb6a00000_3f800000;
        coeff_rom[990] = 64'hb6a00000_3f800000;
        coeff_rom[991] = 64'hb6a00000_3f800000;
        coeff_rom[992] = 64'hb6a00000_3f800000;
        coeff_rom[993] = 64'hb6a00000_3f800000;
        coeff_rom[994] = 64'hb9f38000_3f800100;
        coeff_rom[995] = 64'hb6800000_3f800000;
        coeff_rom[996] = 64'hb6800000_3f800000;
        coeff_rom[997] = 64'hb6800000_3f800000;
        coeff_rom[998] = 64'hb6800000_3f800000;
        coeff_rom[999] = 64'hb6800000_3f800000;
        coeff_rom[1000] = 64'hb6800000_3f800000;
        coeff_rom[1001] = 64'hb6800000_3f800000;
        coeff_rom[1002] = 64'hb9f70000_3f800100;
        coeff_rom[1003] = 64'hb6400000_3f800000;
        coeff_rom[1004] = 64'hb6400000_3f800000;
        coeff_rom[1005] = 64'hb6400000_3f800000;
        coeff_rom[1006] = 64'hb6400000_3f800000;
        coeff_rom[1007] = 64'hb6400000_3f800000;
        coeff_rom[1008] = 64'hb6400000_3f800000;
        coeff_rom[1009] = 64'hb6400000_3f800000;
        coeff_rom[1010] = 64'hb6400000_3f800000;
        coeff_rom[1011] = 64'hb6400000_3f800000;
        coeff_rom[1012] = 64'hb6400000_3f800000;
        coeff_rom[1013] = 64'hb6400000_3f800000;
        coeff_rom[1014] = 64'hb9fc8000_3f800100;
        coeff_rom[1015] = 64'hb6000000_3f800000;
        coeff_rom[1016] = 64'hb6000000_3f800000;
        coeff_rom[1017] = 64'hb6000000_3f800000;
        coeff_rom[1018] = 64'hb6000000_3f800000;
        coeff_rom[1019] = 64'hb6000000_3f800000;
        coeff_rom[1020] = 64'hb6000000_3f800000;
        coeff_rom[1021] = 64'hb6000000_3f800000;
        coeff_rom[1022] = 64'hb6000000_3f800000;
        coeff_rom[1023] = 64'hb6000000_3f800000;
    end

    wire input_nonfinite = (in_gate[30:23] == 8'hff) ||
                           (in_up[30:23] == 8'hff);
    wire input_negative_tail = !input_nonfinite && in_gate[31] &&
                               (in_gate[30:0] >= ABS_16);
    wire input_positive_tail = !input_nonfinite && !in_gate[31] &&
                               (in_gate[30:0] >= ABS_16);
    wire [9:0] input_segment = segment_index(in_gate);

    reg [6:0] reserved_count;
    wire output_pop = out_valid && out_ready;
    // Keep the local capacity predicate independent of the lifecycle abort.
    // Integrators can quarantine both sides of a boundary without propagating
    // an abort through this leaf's reservation counter and upstream ready cone.
    assign in_ready_core = rst_n &&
                           (reserved_count < RESERVE_DEPTH[6:0]);
    assign in_ready = in_ready_core && !abort;
    wire input_accept = in_valid && in_ready;

    // Register the complete ROM request before the coefficient memory. This keeps
    // lane selection and segment decode off the BRAM address
    // pins while retaining one accepted scalar per cycle.
    reg        request_valid;
    reg [9:0]  request_segment;
    reg [31:0] request_gate;
    reg [31:0] request_up;
    reg        request_last;
    reg        request_nonfinite;
    reg        request_negative_tail;
    reg        request_positive_tail;
    always @(posedge clk) begin
        if (!rst_n || abort) begin
            request_valid <= 1'b0;
        end else begin
            request_valid <= input_accept;
            if (input_accept) begin
                request_segment <= input_segment;
                request_gate <= in_gate;
                request_up <= in_up;
                request_last <= in_last;
                request_nonfinite <= input_nonfinite;
                request_negative_tail <= input_negative_tail;
                request_positive_tail <= input_positive_tail;
            end
        end
    end

    // Synchronous ROM read plus metadata capture. The tail modes override the
    // fetched coefficient on the following cycle without changing pipeline shape.
    reg        rom_valid;
    reg [63:0] rom_coeff;
    reg [31:0] rom_gate;
    reg [31:0] rom_up;
    reg        rom_last;
    reg        rom_nonfinite;
    reg        rom_negative_tail;
    reg        rom_positive_tail;
    always @(posedge clk) begin
        if (!rst_n || abort) begin
            rom_valid <= 1'b0;
        end else begin
            rom_valid <= request_valid;
            if (request_valid) begin
                rom_coeff <= coeff_rom[request_segment];
                rom_gate <= request_nonfinite ? ZERO_F32 : request_gate;
                rom_up <= request_nonfinite ? ZERO_F32 : request_up;
                rom_last <= request_last;
                rom_nonfinite <= request_nonfinite;
                rom_negative_tail <= request_negative_tail;
                rom_positive_tail <= request_positive_tail;
            end
        end
    end

    wire [31:0] selected_slope = (rom_nonfinite || rom_negative_tail) ? ZERO_F32 :
                                 rom_positive_tail ? ONE_F32 : rom_coeff[31:0];
    wire [31:0] selected_intercept = (rom_nonfinite || rom_negative_tail ||
                                      rom_positive_tail) ? ZERO_F32 : rom_coeff[63:32];
    wire arith_rst_n = rst_n && !abort;

    wire        gate_mul_valid;
    wire [31:0] gate_mul;
    fmul #(.MANT_W(FMT_FP32_MANT)) u_gate_mul (
        .clk(clk), .rst_n(arith_rst_n), .valid_in(rom_valid),
        .a(rom_gate), .b(selected_slope),
        .valid_out(gate_mul_valid), .out(gate_mul)
    );

    // Carry the intercept to the first arithmetic handoff, UP to the final
    // multiplier, and scalar metadata through the complete fixed-latency path.
    reg [31:0] intercept_pipe [0:FP32_MUL_LATENCY-1];
    localparam integer UP_DELAY = FP32_MUL_LATENCY + 1 + FP32_ADD_LATENCY;
    // result_valid becomes visible one cycle before the wrapper enqueues it; index
    // META_DELAY-1 must therefore hold the matching scalar on that enqueue edge.
    localparam integer META_DELAY = FP32_MUL_LATENCY + 1 + FP32_ADD_LATENCY +
                                    FP32_MUL_LATENCY;
    reg [31:0] up_pipe [0:UP_DELAY-1];
    reg        last_pipe [0:META_DELAY-1];
    reg        nonfinite_pipe [0:META_DELAY-1];
    integer pipe_i;
    always @(posedge clk) begin
        intercept_pipe[0] <= selected_intercept;
        for (pipe_i = 1; pipe_i < FP32_MUL_LATENCY; pipe_i = pipe_i + 1)
            intercept_pipe[pipe_i] <= intercept_pipe[pipe_i-1];

        up_pipe[0] <= rom_up;
        for (pipe_i = 1; pipe_i < UP_DELAY; pipe_i = pipe_i + 1)
            up_pipe[pipe_i] <= up_pipe[pipe_i-1];

        last_pipe[0] <= rom_last;
        nonfinite_pipe[0] <= rom_nonfinite;
        for (pipe_i = 1; pipe_i < META_DELAY; pipe_i = pipe_i + 1) begin
            last_pipe[pipe_i] <= last_pipe[pipe_i-1];
            nonfinite_pipe[pipe_i] <= nonfinite_pipe[pipe_i-1];
        end
    end

    wire        silu_valid;
    wire [31:0] silu_value;
    fadd #(.MANT_W(FMT_FP32_MANT)) u_intercept_add (
        .clk(clk), .rst_n(arith_rst_n), .valid_in(gate_mul_valid),
        .a(gate_mul), .b(intercept_pipe[FP32_MUL_LATENCY-1]),
        .valid_out(silu_valid), .out(silu_value)
    );

    wire        result_valid;
    wire [31:0] result_value;
    fmul #(.MANT_W(FMT_FP32_MANT)) u_up_mul (
        .clk(clk), .rst_n(arith_rst_n), .valid_in(silu_valid),
        .a(silu_value), .b(up_pipe[UP_DELAY-1]),
        .valid_out(result_valid), .out(result_value)
    );

    wire result_saturated = result_value[30:0] == MAX_FIN;
    wire [34:0] result_payload = {
        result_saturated,
        nonfinite_pipe[META_DELAY-1],
        last_pipe[META_DELAY-1],
        result_value
    };

    // Every accepted scalar reserves one of 64 total output slots before entering
    // the non-stallable arithmetic pipeline. Results enter a synchronous block-RAM
    // FIFO before its prefetch register, absorbing arbitrary downstream backpressure
    // without dropping or reordering a fixed-latency result.
    (* ram_style = "block" *) reg [34:0] fifo_mem [0:FIFO_DEPTH-1];
    reg [FIFO_PTR_W-1:0] fifo_read_ptr;
    reg [FIFO_PTR_W-1:0] fifo_write_ptr;
    reg [FIFO_PTR_W:0] fifo_count;
    reg [34:0] fifo_read_data;
    assign {out_status, out_last, out_data} = fifo_read_data;
    wire fifo_write_enable = rst_n && !abort && result_valid;
    wire fifo_read_enable = rst_n && !abort && (fifo_count != 0) &&
                            (!out_valid || output_pop);
`ifdef FORMAL
    assign formal_reserved_count = reserved_count;
    assign formal_fifo_count = fifo_count;
    assign formal_fifo_write_enable = fifo_write_enable;
    assign formal_fifo_read_enable = fifo_read_enable;
    // Stream-control proofs intentionally abstract stored arithmetic payloads.
    (* anyseq *) reg [34:0] formal_fifo_read_payload;
`endif

    // Separate single write and synchronous read processes match Vivado's
    // simple-dual-port block-RAM inference template.
    always @(posedge clk) begin
        if (fifo_write_enable)
            fifo_mem[fifo_write_ptr] <= result_payload;
    end

    // The payload register deliberately has no reset: only out_valid defines its
    // observability, and a resettable read register blocks RAMB18 inference.
    always @(posedge clk) begin
        if (fifo_read_enable) begin
`ifdef FORMAL
            fifo_read_data <= formal_fifo_read_payload;
`else
            fifo_read_data <= fifo_mem[fifo_read_ptr];
`endif
        end
    end

    always @(posedge clk) begin
        if (!rst_n || abort) begin
            out_valid <= 1'b0;
        end else if (fifo_read_enable) begin
            out_valid <= 1'b1;
        end else if (output_pop) begin
            out_valid <= 1'b0;
        end
    end

    always @(posedge clk) begin
        if (!rst_n || abort) begin
            reserved_count <= 7'd0;
        end else begin
            case ({input_accept, output_pop})
                2'b10: reserved_count <= reserved_count + 7'd1;
                2'b01: reserved_count <= reserved_count - 7'd1;
                default: reserved_count <= reserved_count;
            endcase
        end
    end

    always @(posedge clk) begin
        if (!rst_n || abort) begin
            fifo_read_ptr <= {FIFO_PTR_W{1'b0}};
            fifo_write_ptr <= {FIFO_PTR_W{1'b0}};
            fifo_count <= {(FIFO_PTR_W+1){1'b0}};
        end else begin
            if (fifo_write_enable)
                fifo_write_ptr <= fifo_write_ptr + 1'b1;
            if (fifo_read_enable)
                fifo_read_ptr <= fifo_read_ptr + 1'b1;
            case ({fifo_write_enable, fifo_read_enable})
                2'b10: fifo_count <= fifo_count + 1'b1;
                2'b01: fifo_count <= fifo_count - 1'b1;
                default: fifo_count <= fifo_count;
            endcase
        end
    end
endmodule

/* verilator lint_on SYMRSVDWORD */
`default_nettype wire
